ERROR - 2022-03-06 13:49:00 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-03-06 13:49:00 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\wamp64\www\desafio-skysolar\api\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\wamp64\www\desafio-skysolar\api\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\wamp64\www\desafio-skysolar\api\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\wamp64\www\desafio-skysolar\api\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\wamp64\www\desafio-skysolar\api\app\Controllers\Pessoas.php(53): CodeIgniter\BaseModel->findAll()
#5 C:\wamp64\www\desafio-skysolar\api\system\CodeIgniter.php(832): App\Controllers\Pessoas->list()
#6 C:\wamp64\www\desafio-skysolar\api\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pessoas))
#7 C:\wamp64\www\desafio-skysolar\api\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\wamp64\www\desafio-skysolar\api\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
